# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controllerUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_forward = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_forward.setGeometry(QtCore.QRect(90, 520, 71, 61))
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.pushButton_backward = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_backward.setGeometry(QtCore.QRect(90, 660, 71, 61))
        self.pushButton_backward.setObjectName("pushButton_backward")
        self.pushButton_left = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left.setGeometry(QtCore.QRect(20, 590, 71, 61))
        self.pushButton_left.setObjectName("pushButton_left")
        self.pushButton_right = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_right.setGeometry(QtCore.QRect(160, 590, 71, 61))
        self.pushButton_right.setObjectName("pushButton_right")
        self.pushButton_initialize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_initialize.setGeometry(QtCore.QRect(90, 590, 71, 61))
        self.pushButton_initialize.setObjectName("pushButton_initialize")
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setGeometry(QtCore.QRect(10, 10, 581, 481))
        self.labelCamera.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCamera.setObjectName("labelCamera")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(490, 510, 91, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_bodyStatus_rect = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_bodyStatus_rect.setObjectName("radioButton_bodyStatus_rect")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_bodyStatus_rect)
        self.gridLayout.addWidget(self.radioButton_bodyStatus_rect, 0, 0, 1, 1)
        self.radioButton_bodyStatus_crab = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_bodyStatus_crab.setObjectName("radioButton_bodyStatus_crab")
        self.buttonGroup_2.addButton(self.radioButton_bodyStatus_crab)
        self.gridLayout.addWidget(self.radioButton_bodyStatus_crab, 3, 0, 1, 1)
        self.radioButton_bodyStatus_highLeg = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_bodyStatus_highLeg.setObjectName("radioButton_bodyStatus_highLeg")
        self.buttonGroup_2.addButton(self.radioButton_bodyStatus_highLeg)
        self.gridLayout.addWidget(self.radioButton_bodyStatus_highLeg, 1, 0, 1, 1)
        self.radioButton_bodyStatus_hexagon = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_bodyStatus_hexagon.setObjectName("radioButton_bodyStatus_hexagon")
        self.buttonGroup_2.addButton(self.radioButton_bodyStatus_hexagon)
        self.gridLayout.addWidget(self.radioButton_bodyStatus_hexagon, 2, 0, 1, 1)
        self.radioButton_bodyStatus_upDown = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_bodyStatus_upDown.setObjectName("radioButton_bodyStatus_upDown")
        self.buttonGroup_2.addButton(self.radioButton_bodyStatus_upDown)
        self.gridLayout.addWidget(self.radioButton_bodyStatus_upDown, 4, 0, 1, 1)
        self.radioButton_cameraStatus = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_cameraStatus.setGeometry(QtCore.QRect(10, 500, 121, 22))
        self.radioButton_cameraStatus.setObjectName("radioButton_cameraStatus")
        self.pushButton_steps = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_steps.setGeometry(QtCore.QRect(400, 530, 81, 34))
        self.pushButton_steps.setObjectName("pushButton_steps")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_forward.setText(_translate("MainWindow", "前"))
        self.pushButton_backward.setText(_translate("MainWindow", "后"))
        self.pushButton_left.setText(_translate("MainWindow", "左"))
        self.pushButton_right.setText(_translate("MainWindow", "右"))
        self.pushButton_initialize.setText(_translate("MainWindow", "初始"))
        self.labelCamera.setText(_translate("MainWindow", "摄像头显示"))
        self.radioButton_bodyStatus_rect.setText(_translate("MainWindow", "四边形"))
        self.radioButton_bodyStatus_crab.setText(_translate("MainWindow", "螃蟹"))
        self.radioButton_bodyStatus_highLeg.setText(_translate("MainWindow", "高脚"))
        self.radioButton_bodyStatus_hexagon.setText(_translate("MainWindow", "六边形"))
        self.radioButton_bodyStatus_upDown.setText(_translate("MainWindow", "翻转态"))
        self.radioButton_cameraStatus.setText(_translate("MainWindow", "摄像头"))
        self.pushButton_steps.setText(_translate("MainWindow", "上楼梯"))
